# Ирисы

### Один из самых часто используемых датасетов - познакомьтесь с ним поближе

https://archive.ics.uci.edu/ml/datasets/iris

либо из папки datasets

### Шаг 1. Импортируем библиотеки.

In [19]:
import pandas as pd
import numpy as np

### Шаг 2. Импортируем датасет

In [3]:
# path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
path = '../datasets/iris.data'

### Шаг 3. Записываем его в переменную iris.

In [5]:
iris=pd.read_csv('/home/ambr2000/Downloads/Iris.csv')
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

### Шаг 4. Создайте дополнительные колонки.

In [9]:
# 1. sepal_length (in cm)
# 2. sepal_width (in cm)
# 3. petal_length (in cm)
# 4. petal_width (in cm)
# 5. class
iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']]\
    = iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']]
iris.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sepal_length,sepal_width,petal_length,petal_width,class
0,1,5.1,3.5,1.4,0.2,Iris-setosa,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa,5.0,3.6,1.4,0.2,Iris-setosa

### Шаг 5. Есть ли пропущенные значения?

In [14]:
iris.isnull().values.any()

False

### Шаг 6. Зададим значение NaN для строк с 10 по 29 колонки 'petal_length'

In [21]:
from numpy import nan as NaN
iris.loc[9:28, 'petal_length'] = NaN

### Шаг 7. Отлично, теперь заменим NaN на 1.0

In [22]:
iris.fillna(1.0)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sepal_length,sepal_width,petal_length,petal_width,class
0,1,5.1,3.5,1.4,0.2,Iris-setosa,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica,5.9,3.0,5.1,1.8,Iris-virginica

### Шаг 8. Удалим колонку class

In [23]:
iris.drop('class',axis=1)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sepal_length,sepal_width,petal_length,petal_width
0,1,5.1,3.5,1.4,0.2,Iris-setosa,5.1,3.5,1.4,0.2
1,2,4.9,3.0,1.4,0.2,Iris-setosa,4.9,3.0,1.4,0.2
2,3,4.7,3.2,1.3,0.2,Iris-setosa,4.7,3.2,1.3,0.2
3,4,4.6,3.1,1.5,0.2,Iris-setosa,4.6,3.1,1.5,0.2
4,5,5.0,3.6,1.4,0.2,Iris-setosa,5.0,3.6,1.4,0.2
...,...,...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,6.7,3.0,5.2,2.3
146,147,6.3,2.5,5.0,1.9,Iris-virginica,6.3,2.5,5.0,1.9
147,148,6.5,3.0,5.2,2.0,Iris-virginica,6.5,3.0,5.2,2.0
148,149,6.2,3.4,5.4,2.3,Iris-virginica,6.2,3.4,5.4,2.3
149,150,5.9,3.0,5.1,1.8,Iris-virginica,5.9,3.0,5.1,1.8

### Шаг 9. Запишем NaN в первые 3 строки (во все колонки)

In [25]:
iris.iloc[:3,:]=NaN
iris.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sepal_length,sepal_width,petal_length,petal_width,class
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,4.6,3.1,1.5,0.2,Iris-setosa,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,5.0,3.6,1.4,0.2,Iris-setosa,5.0,3.6,1.4,0.2,Iris-setosa

### Шаг 10. Удалим строки, в которых встречается NaN

In [29]:
iris=iris.dropna()

### Шаг 11. Сбросим индекс - начнем его опять с 0.

In [30]:
iris.reset_index()

,index,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sepal_length,sepal_width,petal_length,petal_width,class
0,3,4.0,4.6,3.1,1.5,0.2,Iris-setosa,4.6,3.1,1.5,0.2,Iris-setosa
1,4,5.0,5.0,3.6,1.4,0.2,Iris-setosa,5.0,3.6,1.4,0.2,Iris-setosa
2,5,6.0,5.4,3.9,1.7,0.4,Iris-setosa,5.4,3.9,1.7,0.4,Iris-setosa
3,6,7.0,4.6,3.4,1.4,0.3,Iris-setosa,4.6,3.4,1.4,0.3,Iris-setosa
4,7,8.0,5.0,3.4,1.5,0.2,Iris-setosa,5.0,3.4,1.5,0.2,Iris-setosa
...,...,...,...,...,...,...,...,...,...,...,...,...
122,145,146.0,6.7,3.0,5.2,2.3,Iris-virginica,6.7,3.0,5.2,2.3,Iris-virginica
123,146,147.0,6.3,2.5,5.0,1.9,Iris-virginica,6.3,2.5,5.0,1.9,Iris-virginica
124,147,148.0,6.5,3.0,5.2,2.0,Iris-virginica,6.5,3.0,5.2,2.0,Iris-virginica
125,148,149.0,6.2,3.4,5.4,2.3,Iris-virginica,6.2,3.4,5.4,2.3,Iris-virginica
126,149,150.0,5.9,3.0,5.1,1.8,Iris-virginica,5.9,3.0,5.1,1.8,Iris-virginica

### Шаг 12. Бонус: Напишите свой вопрос и ответьте на него.

In [31]:
#сравните среднее арифметическое и моду длины лепестка

In [33]:
iris.mode()['petal_length'][0]

1.5

In [35]:
iris['petal_length'].mean()

4.174015748031496